var quiz1 = new quiz('')
globalquiz = quiz1
nextmodule('m1')
nextset('set 1')
addproblem("Which one of the following is a Class C IP address?",'c',"10.10.14.118","191.200.199.199","204.67.118.54")
addproblem("Segmentation of a data stream happens at which layer of the OSI model?",'b',"Network","Transport","Data-link")
addproblem("Multiple stations receive the frame and each of them processes to check if the frame is intended for it. What kind of frame would this be?",'a',"Broadcast","Unicast","Multicast")
addproblem("You have an IP of 156.233.42.56 with a subnet mask of 7 bits. How many hosts and subnets are possible assuming that subnet 0 is not used? ",'b',"510 subnets and 126 hosts","126 subnets and 510 hosts","512 subnets and 128 hosts")
addproblem("Two sub layers of OSI Data Link layer are which of the following?",'a',"Logical Link Control, Media Access Control","Media Access Control, Physical Layer Control","Data Link Control, Physical Layer Control")
addproblem("MAC addresses are the feature of ______________layer.",'a',"Data-link","Physical","None of the above")
addproblem("Which of the below choices describe distributed switching?",'b',"It requires smart packeting."," It is faster than centralised switching.","None of the above")
nextset('set 2')
addproblem("MAC is to Ethernet what ________is to Frame Relay.",'a',"DLCI","LCI","PVC")
addproblem("Which is a device used to connect ISDN Basic Rate Interface (BRI) connections to other interfaces, such as EIA/TIA-232 on a router?",'b',"ISDN power adapter","ISDN terminal adapter","RJ-11 cable")
addproblem("Which of the following is true of a Switch?",'c',"Switches forward packets based on Layer3 protocol.","Switches forward packets based on IP address.","Switches forward packets based on MAC address.")
addproblem("Bridges are software based where as switches are ______ based.",'c',"CISC","RISC","ASIC")
addproblem("What is the value of VLAN Tagged Protocol Identifier as an identification of Virtual Bridged Local Area Network Standards?",'c',"Hex range 0x0-00 to 0x-F-FF","Hex 0x-F-FF fixed","Hex 0x81-00")
addproblem("The IPX is a universal standard for inter-LAN communication.",'b',"True","False")
addproblem("Identify the correct statements about “source-route bridging”.",'a'," It uses a RIF within each packet to identify the destination.","It sends the desitnation frames directly to the nodes.","The dia should not exceed 5.")

