var quiz1 = new quiz('')
globalquiz = quiz1
nextmodule('m1')
nextset('set 1')
addproblem("What does HTML stand for?",'a',"Hyper Text Markup Language","Hot Mail ","How to Make Lasagna")
addproblem("How many tags are in a regular element?",'c',"2","1","3")
addproblem("what is the difference in an opening tag and a closing tag? ",'b',"Opening tag has a / in front","Closing tag has a / in front","There is no difference")
addproblem("Which HTML tag is used to define an internal style sheet?",'c',"<css>","<script>","<style>")
addproblem("Which is the correct CSS syntax?",'b',"{body;color:black;}","{body:color=black;}","body:color=black;")
addproblem("Which property is used to change the background color?",'a',"background-color","color","bgcolor")
addproblem("Inside which HTML element do we put the JavaScript?",'a',"<script>","<javascript>","<js>")
addproblem("Where is the correct place to insert a JavaScript?",'b',"The <body> section","The <head> section","Both the <head> section and the <body> section are correct")
addproblem("How can you make a numbered list?",'a',"<list>","<ul>","<ol>")
nextset('set 2')
addproblem("What does CSS stand for?",'b',"Computer Style Sheets","Cascading Style Sheets","Creative Style Sheets")
addproblem("Where in an HTML document is the correct place to refer to an external style sheet?",'a',"In the <head> section","In the <body> section","At the end of the document")
addproblem("< br/>What type of tag is this?",'a',"Break tag","Break tag","An opening tag")
addproblem("Who is making the Web standards?",'b',"Microsoft","The World Wide Web Consortium","Google")
addproblem("Choose the correct HTML element for the largest heading:",'a',"<h1>","<h6>","<heading>")
addproblem("How do you add a background color for all <h1> elements?",'c',"all.h1 {background-color:#FFFFFF;}","h1.all {background-color:#FFFFFF;}","h1 {background-color:#FFFFFF;}")
addproblem("Which property is used to change the font of an element?",'a',"font-family","font","Both font-family and font can be used")
addproblem("Which property is used to change the left margin of an element?",'c',"margin-left","indent","padding-left")
nextmodule('m2')
nextset('set 1')
addproblem("Which of these elements are all <table> elements?",'b',"<table><head><tfoot>","<table><tr><td>","<table><tr><tt>")
addproblem("How to write an IF statement in JavaScript?",'b',"if i == 5 then","if i = 5","if (i == 5)")
addproblem("How do you select all p elements inside a div element?",'b',"div + p","div.p","div p")
addproblem("What is the default value of the position property?",'c',"relative","static","fixed")
addproblem("Which event occurs when the user clicks on an HTML element?",'b',"onchange","onclick","onmouseclick")
addproblem("How do you declare a JavaScript variable?",'a',"var carName;","variable carName;","v carName;")
nextset('set 2')
addproblem("Which HTML element defines the title of a document?",'b',"<head>","<title>","<meta>")
addproblem("Which HTML attribute specifies an alternate text for an image, if the image cannot be displayed?",'a',"alt","src","longdesc")
addproblem("Choose the correct HTML element to define important text",'c',"<i>","<b>","<strong>")
addproblem("Choose the correct HTML element to define emphasized text",'a',"<i>","<em>","<italic>")
addproblem("Which character is used to indicate an end tag?",'c',"&","#","/")
addproblem("How can you make a bulleted list?",'a',"<ol>","<list>","ul")