var quiz1 = new quiz('')
globalquiz = quiz1
nextmodule('m1')
nextset('set 1')
addproblem("Which of the following statements should be used to obtain a remainder after dividing 3.14 by 2.1 ?",'c',"rem = 3.14 % 2.1;","rem = modf(3.14, 2.1);","rem = fmod(3.14, 2.1);")
addproblem("Which of the following special symbol allowed in a variable name?",'a',"_ (underscore)","* (asterisk)","- (hyphen)")
addproblem("In which header file is the NULL macro defined?",'b',"stdio.h","stdio.h and stddef.h","stddef.h")
addproblem("What is (void*)0?",'a',"Representation of NULL pointer","Error","None of above")
addproblem("What does fp point to in the program ?",'c',"The first character in the file","The name of the file.","A structure which contains a char pointer which points to the first character of a file.")
addproblem("If the two strings are identical, then strcmp() function returns",'b',"-1","0","1")
addproblem("Which of the following is not logical operator?",'a',"&","!","&&")
addproblem("The keyword used to transfer control from a function back to the calling function is",'c',"switch","goto","return")
nextset('set 2')
addproblem("Which of the following type of class allows only one object of it to be created?",'c',"Virtual class","Abstract class","Singleton class")
addproblem("Which of the following is not a type of constructor?",'a',"Friend constructor","Copy constructor","Default constructor")
addproblem("Which of the following is not the member of class?",'b',"Virtual function","Friend function","Static function")
addproblem("Which of the following concepts means determining at runtime what method to invoke?",'c',"Dynamic loading","Data hiding","Dynamic binding")
addproblem("Where the default value of parameter have to be specified?",'a',"Function prototype","Function call","Function definition")
addproblem("Can a class have virtual destructor?",'b',"YES","NO")
addproblem("Destructor has the same name as the constructor and it is preceded by ______ .",'c',"?","!","~")
addproblem("For automatic objects, constructors and destructors are called each time the objects",'a',"enter and leave scope","are destroyed","are constructed")
nextmodule('m2')
nextset('set 1')
addproblem("Which is a reserved word in the Java programming language?",'a',"native","subclasses","method")
addproblem("Which is a valid keyword in java?",'c',"string","Float","interface")
addproblem("What is the name of the method used to start a thread execution?",'b',"init();","start();","run();")
addproblem("Which are methods of the Object class?",'a',"notify(); & notifyAll();","interrupt(); & notify();")
addproblem("Which cannot directly cause a thread to stop executing?",'c',"Calling read() method on an InputStream object.","Calling the wait() method on an object.","Calling notify() method on an object.")
addproblem("Which collection class allows you to grow or shrink its size and provides indexed access to its elements, but whose methods are not synchronized?",'a',"java.util.ArrayList","java.util.HashSet","java.util.List")
addproblem("Which interface does java.util.Hashtable implement?",'b',"Java.util.List","Java.util.Map","Java.util.Collection")
nextset('set 2')
addproblem("Which of the following cannot be checked in a switch-case statement?",'b',"Character","Float","Integer")
addproblem("Input/output function prototypes and macros are defined in which header file?",'a',"stdio.h","conio.h","dos.h")
addproblem("Which header file should be included to use functions like malloc() and calloc()?",'c',"memory.h","string.h","stdlib.h")
addproblem("Which of the following access specifies is used in a class definition by default?",'a',"Private","Protected","Public")
addproblem("What is the numerical range of char?",'c',"0 to 32767","-256 to 255","0 to 65535")
addproblem("Which of the following are Java reserved words?",'a',"import,default","implement,run","import,null")
addproblem("Which of the following keywords is used to control access to a class member?",'b',"Private","Protected","Public")
addproblem("Which method registers a thread in a thread scheduler?",'b',"run();","start();","construct();")
